### ISSUE TITLE
setbed causing internal error

### ISSUE THREAD

**Issue by jamespandaz** [ThatKingGuy/BedwarsPlus#6]
When I try to setup an arena setbed is causing an internal error. This also happens with setspawn and setmainlobby.

Console Output:
```
11.07 11:17:56 [Server] Server thread/INFO JJJ4006 issued server command: /bwa setbed lava Blue
11.07 11:17:56 [Server] Server thread/ERROR null
11.07 11:17:56 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'bwa' in plugin BedwarsPlus v3.3
11.07 11:17:56 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:761) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:1936) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1779) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1732) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:28) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1061) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1054) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1038) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:970) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO at java.lang.Thread.run(Thread.java:829) [?:?]
11.07 11:17:56 [Server] INFO Caused by: java.lang.NoSuchMethodError: 'org.bukkit.block.Block org.bukkit.entity.Player.getTargetBlock(int)'
11.07 11:17:56 [Server] INFO at com.gabe.bedwars.commands.admin.SetBedCommand.<init>(SetBedCommand.java:24) ~[?:?]
11.07 11:17:56 [Server] INFO at com.gabe.bedwars.Bedwars.onCommand(Bedwars.java:324) ~[?:?]
11.07 11:17:56 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot_1.16.5.jar:3096-Spigot-9fb885e-296df56]
11.07 11:17:56 [Server] INFO ... 19 more
```

**Comment by ThatKingGuy** [comment]
You need to use Paper 1.16.5
